<a href='/comp/Moves/Basic'>Basic Moves</a>
<a href='/comp/Balance'>Balance</a>
<a href='/comp/Moves/Balance'>Balance Moves</a>
<a href='/comp/Core/Condition'>Conditions</a>
<a href='/comp/Statuses'>Statuses</a>
<a href='/comp/Combat'>Combat</a>
<a href='/comp/Techniques'>Techniques</a>
<a href='/comp/Techniques/Training'>The Training Move</a>
<a href='/comp/Techniques/Mastery'>Technique Mastery</a>